version: "3.9"
services:
  db:
    image: postgres:alpine3.16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "${POSTGRES_DATA:-./data/postgres/data}:/var/lib/postgresql/data"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-test}"
    restart: always



  backend:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8001}:8000"
    environment:
      PORT: 8000
    depends_on:
      - db
